INSERT INTO players (name)
VALUES ('Novak Djokovic'),
       ('Rafael Nadal'),
       ('Roger Federer'),
       ('Carlos Alcaraz'),
       ('Jannik Sinner'),
       ('Daniil Medvedev'),
       ('Alexander Zverev'),
       ('Stefanos Tsitsipas'),
       ('Andrey Rublev'),
       ('Casper Ruud');

INSERT INTO matches (player1, player2, winner)
VALUES (1, 2, 1),
       (3, 4, 4),
       (5, 6, 6),
       (7, 8, 7),
       (9, 10, 10),
       (1, 5, 5),
       (2, 8, 2),
       (3, 9, 3),
       (4, 10, 10),
       (6, 7, 6),
       (1, 3, 1),
       (2, 4, 4),
       (5, 7, 5),
       (6, 9, 9),
       (8, 10, 8),
       (1, 10, 10),
       (2, 6, 2),
       (3, 7, 7),
       (4, 8, 8),
       (5, 9, 5);